/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiContextRouteImport } from './routes/ai-context'
import { Route as CaseReviewRouteImport } from './routes/case-review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewCaseRouteImport } from './routes/new-case'
import { Route as PreprocessingRouteImport } from './routes/preprocessing'
import { Route as Step2RouteImport } from './routes/step2'
import { Route as Step3RouteImport } from './routes/step3'
import { Route as Step4RouteImport } from './routes/step4'
import { Route as Step5RouteImport } from './routes/step5'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiContextRoute = AiContextRouteImport.update({
  id: '/ai-context',
  path: '/ai-context',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseReviewRoute = CaseReviewRouteImport.update({
  id: '/case-review',
  path: '/case-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewCaseRoute = NewCaseRouteImport.update({
  id: '/new-case',
  path: '/new-case',
  getParentRoute: () => rootRouteImport,
} as any)
const PreprocessingRoute = PreprocessingRouteImport.update({
  id: '/preprocessing',
  path: '/preprocessing',
  getParentRoute: () => rootRouteImport,
} as any)
const Step2Route = Step2RouteImport.update({
  id: '/step2',
  path: '/step2',
  getParentRoute: () => rootRouteImport,
} as any)
const Step3Route = Step3RouteImport.update({
  id: '/step3',
  path: '/step3',
  getParentRoute: () => rootRouteImport,
} as any)
const Step4Route = Step4RouteImport.update({
  id: '/step4',
  path: '/step4',
  getParentRoute: () => rootRouteImport,
} as any)
const Step5Route = Step5RouteImport.update({
  id: '/step5',
  path: '/step5',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-context': typeof AiContextRoute
  '/case-review': typeof CaseReviewRoute
  '/login': typeof LoginRoute
  '/new-case': typeof NewCaseRoute
  '/preprocessing': typeof PreprocessingRoute
  '/step2': typeof Step2Route
  '/step3': typeof Step3Route
  '/step4': typeof Step4Route
  '/step5': typeof Step5Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-context': typeof AiContextRoute
  '/case-review': typeof CaseReviewRoute
  '/login': typeof LoginRoute
  '/new-case': typeof NewCaseRoute
  '/preprocessing': typeof PreprocessingRoute
  '/step2': typeof Step2Route
  '/step3': typeof Step3Route
  '/step4': typeof Step4Route
  '/step5': typeof Step5Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-context': typeof AiContextRoute
  '/case-review': typeof CaseReviewRoute
  '/login': typeof LoginRoute
  '/new-case': typeof NewCaseRoute
  '/preprocessing': typeof PreprocessingRoute
  '/step2': typeof Step2Route
  '/step3': typeof Step3Route
  '/step4': typeof Step4Route
  '/step5': typeof Step5Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-context'
    | '/case-review'
    | '/login'
    | '/new-case'
    | '/preprocessing'
    | '/step2'
    | '/step3'
    | '/step4'
    | '/step5'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-context'
    | '/case-review'
    | '/login'
    | '/new-case'
    | '/preprocessing'
    | '/step2'
    | '/step3'
    | '/step4'
    | '/step5'
  id:
    | '__root__'
    | '/'
    | '/ai-context'
    | '/case-review'
    | '/login'
    | '/new-case'
    | '/preprocessing'
    | '/step2'
    | '/step3'
    | '/step4'
    | '/step5'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiContextRoute: typeof AiContextRoute
  CaseReviewRoute: typeof CaseReviewRoute
  LoginRoute: typeof LoginRoute
  NewCaseRoute: typeof NewCaseRoute
  PreprocessingRoute: typeof PreprocessingRoute
  Step2Route: typeof Step2Route
  Step3Route: typeof Step3Route
  Step4Route: typeof Step4Route
  Step5Route: typeof Step5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-context': {
      id: '/ai-context'
      path: '/ai-context'
      fullPath: '/ai-context'
      preLoaderRoute: typeof AiContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-review': {
      id: '/case-review'
      path: '/case-review'
      fullPath: '/case-review'
      preLoaderRoute: typeof CaseReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-case': {
      id: '/new-case'
      path: '/new-case'
      fullPath: '/new-case'
      preLoaderRoute: typeof NewCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preprocessing': {
      id: '/preprocessing'
      path: '/preprocessing'
      fullPath: '/preprocessing'
      preLoaderRoute: typeof PreprocessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step2': {
      id: '/step2'
      path: '/step2'
      fullPath: '/step2'
      preLoaderRoute: typeof Step2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step3': {
      id: '/step3'
      path: '/step3'
      fullPath: '/step3'
      preLoaderRoute: typeof Step3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step4': {
      id: '/step4'
      path: '/step4'
      fullPath: '/step4'
      preLoaderRoute: typeof Step4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step5': {
      id: '/step5'
      path: '/step5'
      fullPath: '/step5'
      preLoaderRoute: typeof Step5RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiContextRoute: AiContextRoute,
  CaseReviewRoute: CaseReviewRoute,
  LoginRoute: LoginRoute,
  NewCaseRoute: NewCaseRoute,
  PreprocessingRoute: PreprocessingRoute,
  Step2Route: Step2Route,
  Step3Route: Step3Route,
  Step4Route: Step4Route,
  Step5Route: Step5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
